spring.application.name=kafka-demo

# Kde be?í tvoja Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Nastavenie pre consumera
spring.kafka.consumer.group-id=my-demo-group
spring.kafka.consumer.auto-offset-reset=earliest

# Tento riadok hovorí, ?e posielame JSON objekty
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Tieto dva riadky hovoria, ?e prijímame JSON objekty
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*