spring.application.name=kafka-demo

# Kde be?í tvoja Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Nastavenie pre consumera
spring.kafka.consumer.group-id=my-demo-group
spring.kafka.consumer.auto-offset-reset=earliest